# -*- coding: utf-8 -*-
"""iCODEGRU_BOOTCAMP_ASSIGNMENT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWfEMyqEiiavHuwgSJUb5VT_0jBuPdN2
"""

# ============================================================
#   PROJECT 2: Daily Digest CLI
#   Python Bootcamp Mini Project
#   API Used: Open-Meteo (100% FREE — no API key needed!)
# ============================================================

import requests
import json
from datetime import datetime


# ── FUNCTION 1: Fetch weather data from free API ────────────
def fetch_weather():
    print("\n⏳ Fetching weather data...")

    # Open-Meteo is completely free and needs no API key
    # Coordinates below are for Karachi, Pakistan
    url = (
        "https://api.open-meteo.com/v1/forecast"
        "?latitude=24.8607"
        "&longitude=67.0011"
        "&current_weather=true"
        "&hourly=relative_humidity_2m"
        "&timezone=Asia/Karachi"
    )

    try:
        response = requests.get(url, timeout=10)

        # Raise error if request failed
        response.raise_for_status()

        # Convert JSON response to Python dictionary
        data = response.json()
        return data

    except requests.exceptions.ConnectionError:
        print("❌ No internet connection. Please check your network.")
        return None

    except requests.exceptions.Timeout:
        print("❌ Request timed out. Try again later.")
        return None

    except requests.exceptions.HTTPError as e:
        print(f"❌ HTTP Error: {e}")
        return None


# ── FUNCTION 2: Process and display the weather data ────────
def process_weather(data):
    print("\n" + "=" * 45)
    print("       🌤️  DAILY WEATHER DIGEST")
    print("=" * 45)

    # Extract current weather info from the response
    current = data["current_weather"]

    temperature   = current["temperature"]        # in Celsius
    windspeed     = current["windspeed"]          # in km/h
    weather_code  = current["weathercode"]        # WMO code
    time_recorded = current["time"]               # ISO datetime string

    # Get first hour humidity value
    humidity = data["hourly"]["relative_humidity_2m"][0]

    # Convert WMO weather code to human-readable description
    condition = get_weather_condition(weather_code)

    # Display nicely in terminal
    print(f"\n📍 Location     : Karachi, Pakistan")
    print(f"🕐 Time         : {time_recorded}")
    print(f"🌡️  Temperature  : {temperature}°C")
    print(f"💨 Wind Speed   : {windspeed} km/h")
    print(f"💧 Humidity     : {humidity}%")
    print(f"🌤️  Condition    : {condition}")
    print("=" * 45)

    # Return processed info as a dictionary for the report
    return {
        "temperature" : temperature,
        "windspeed"   : windspeed,
        "humidity"    : humidity,
        "condition"   : condition,
        "time"        : time_recorded
    }


# ── FUNCTION 3: Convert WMO code to condition text ──────────
def get_weather_condition(code):
    conditions = {
        0 : "Clear sky ☀️",
        1 : "Mainly clear 🌤️",
        2 : "Partly cloudy ⛅",
        3 : "Overcast ☁️",
        45: "Foggy 🌫️",
        48: "Icy fog 🌫️",
        51: "Light drizzle 🌦️",
        61: "Light rain 🌧️",
        63: "Moderate rain 🌧️",
        65: "Heavy rain 🌧️",
        80: "Rain showers 🌦️",
        95: "Thunderstorm ⛈️",
    }
    # Return matching condition or unknown if code not in list
    return conditions.get(code, f"Unknown (code {code})")


# ── FUNCTION 4: Save report to daily_report.txt ─────────────
def save_report(weather_info):
    filename = "daily_report.txt"

    # Get current date and time
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build report content
    report = f"""
============================================================
                    DAILY DIGEST REPORT
============================================================
Date Generated  : {now}
API Name        : Open-Meteo Weather API (open-meteo.com)
Location        : Karachi, Pakistan
------------------------------------------------------------

WEATHER INFORMATION
-------------------
Temperature     : {weather_info['temperature']}°C
Wind Speed      : {weather_info['windspeed']} km/h
Humidity        : {weather_info['humidity']}%
Condition       : {weather_info['condition']}
Data Time       : {weather_info['time']}

------------------------------------------------------------
Report generated automatically by Daily Digest CLI
============================================================
"""

    try:
        # Write report to file
        with open(filename, "w") as file:
            file.write(report)
        print(f"\n✅ Report saved to '{filename}' successfully!")

    except Exception as e:
        print(f"❌ Could not save report: {e}")


# ── MAIN FUNCTION ────────────────────────────────────────────
def main():
    print("=" * 45)
    print("       DAILY DIGEST CLI")
    print("       Weather Edition 🌤️")
    print("=" * 45)

    # Step 1: Fetch data from API
    data = fetch_weather()

    # Stop if fetch failed
    if data is None:
        print("\n❌ Could not fetch data. Exiting.")
        return

    # Step 2: Process and display data
    weather_info = process_weather(data)

    # Step 3: Save report to file
    save_report(weather_info)

    print("\n✅ Daily Digest complete!")


# ── Run the program ──────────────────────────────────────────
if __name__ == "__main__":
    main()

