# -*- coding: utf-8 -*-
"""iCODEGRU_BOOTCAMP_ASSIGNMENT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xCXxr6_1mmAz9QuNTtKb960yt7rB4Bj
"""

# ============================================================
#   PROJECT 1: Student Management System
#   Python Bootcamp Mini Project
# ============================================================

# This list will store all student records as dictionaries
students = []

# ── HELPER: Calculate grade from marks ──────────────────────
def calculate_grade(marks):
    if marks >= 90:
        return "A+"
    elif marks >= 80:
        return "A"
    elif marks >= 70:
        return "B"
    elif marks >= 60:
        return "C"
    elif marks >= 50:
        return "D"
    else:
        return "F"

# ── FUNCTION 1: Add a new student ───────────────────────────
def add_student():
    print("\n--- Add Student ---")

    student_id = input("Enter Student ID   : ").strip()

    # Check if ID already exists
    for s in students:
        if s["id"] == student_id:
            print("❌ Student ID already exists!")
            return

    name   = input("Enter Student Name : ").strip()
    age    = input("Enter Age          : ").strip()
    course = input("Enter Course       : ").strip()

    # Validate marks input
    while True:
        try:
            marks = float(input("Enter Marks (0-100): ").strip())
            if 0 <= marks <= 100:
                break
            else:
                print("❌ Marks must be between 0 and 100.")
        except ValueError:
            print("❌ Please enter a valid number.")

    # Auto-calculate grade
    grade = calculate_grade(marks)

    # Create student dictionary and add to list
    student = {
        "id"    : student_id,
        "name"  : name,
        "age"   : age,
        "course": course,
        "marks" : marks,
        "grade" : grade
    }
    students.append(student)
    print(f"✅ Student '{name}' added successfully! Grade: {grade}")

# ── FUNCTION 2: View all students ───────────────────────────
def view_all_students():
    print("\n--- All Students ---")

    if len(students) == 0:
        print("No students found.")
        return

    # Print table header
    print(f"\n{'ID':<10} {'Name':<20} {'Age':<5} {'Course':<15} {'Marks':<8} {'Grade'}")
    print("-" * 65)

    # Print each student row
    for s in students:
        print(f"{s['id']:<10} {s['name']:<20} {s['age']:<5} {s['course']:<15} {s['marks']:<8} {s['grade']}")

# ── FUNCTION 3: Search student by ID or Name ────────────────
def search_student():
    print("\n--- Search Student ---")
    keyword = input("Enter Student ID or Name to search: ").strip().lower()

    found = []
    for s in students:
        if keyword in s["id"].lower() or keyword in s["name"].lower():
            found.append(s)

    if len(found) == 0:
        print("❌ No student found.")
    else:
        print(f"\n{'ID':<10} {'Name':<20} {'Age':<5} {'Course':<15} {'Marks':<8} {'Grade'}")
        print("-" * 65)
        for s in found:
            print(f"{s['id']:<10} {s['name']:<20} {s['age']:<5} {s['course']:<15} {s['marks']:<8} {s['grade']}")

# ── FUNCTION 4: Update student information ──────────────────
def update_student():
    print("\n--- Update Student ---")
    student_id = input("Enter Student ID to update: ").strip()

    # Find student by ID
    for s in students:
        if s["id"] == student_id:
            print(f"Found: {s['name']} — leave blank to keep current value")

            new_name   = input(f"New Name   [{s['name']}]  : ").strip()
            new_age    = input(f"New Age    [{s['age']}]   : ").strip()
            new_course = input(f"New Course [{s['course']}]: ").strip()
            new_marks  = input(f"New Marks  [{s['marks']}] : ").strip()

            # Only update if user entered something
            if new_name:   s["name"]   = new_name
            if new_age:    s["age"]    = new_age
            if new_course: s["course"] = new_course
            if new_marks:
                try:
                    marks = float(new_marks)
                    if 0 <= marks <= 100:
                        s["marks"] = marks
                        s["grade"] = calculate_grade(marks)  # recalculate grade
                    else:
                        print("❌ Invalid marks — not updated.")
                except ValueError:
                    print("❌ Invalid marks — not updated.")

            print("✅ Student updated successfully!")
            return

    print("❌ Student ID not found.")

# ── FUNCTION 5: Delete student ──────────────────────────────
def delete_student():
    print("\n--- Delete Student ---")
    student_id = input("Enter Student ID to delete: ").strip()

    for s in students:
        if s["id"] == student_id:
            confirm = input(f"Are you sure you want to delete '{s['name']}'? (yes/no): ").strip().lower()
            if confirm == "yes":
                students.remove(s)
                print("✅ Student deleted successfully!")
            else:
                print("❌ Deletion cancelled.")
            return

    print("❌ Student ID not found.")

# ── MAIN MENU ────────────────────────────────────────────────
def main():
    print("=" * 45)
    print("     STUDENT MANAGEMENT SYSTEM")
    print("=" * 45)

    while True:
        print("\n--- MENU ---")
        print("1. Add Student")
        print("2. View All Students")
        print("3. Search Student")
        print("4. Update Student Information")
        print("5. Delete Student")
        print("6. Exit")

        choice = input("\nEnter your choice (1-6): ").strip()

        if   choice == "1": add_student()
        elif choice == "2": view_all_students()
        elif choice == "3": search_student()
        elif choice == "4": update_student()
        elif choice == "5": delete_student()
        elif choice == "6":
            print("\n👋 Goodbye! Exiting system.")
            break
        else:
            print("❌ Invalid choice. Please enter 1 to 6.")


# ── Run the program ──────────────────────────────────────────
if __name__ == "__main__":
    main()

